print("\n\n")
print("               __       ")
print("              /oo\      Monster: Shia Lebouf")
print("              \__/_     HP: 156/200")
print("              /| | \    Equipped: Fists")
print("     ,       | | | |  ")
print("               |||      ")
print("         ,     |||    , ")
print("               - -      ")
print("")
print("                     _o_      ")
print("                    |\  \     ")
print("      ,      ,      \ \  \    ")
print("                     \ \  \   ")
print("   ,                  | \ii\  ")
print("               ,      | |==|  ")
print("                      \ |  |  GFP 9mm")
print("         ,         ,   \|__|  7/15 9x19 pbm")
print("\n\n\n\n")



print("     _    GFP 9mm             _  Shia Lebouf")
print("    (_)   7/15 9x19 pbm      (s) 156/200")
print("    /|\,-                    /|\ Fists")
print("     |                        |     ")
print("__, / \ _i_,_,,___,_i__,,,_, / \ ,,_")
print("\n\n")
